# Generated by Django 3.2.13 on 2022-05-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tenant', '0002_housepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepayment',
            name='house_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
