# Generated by Django 3.2.6 on 2022-05-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_message_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
