# Generated by Django 3.2.13 on 2022-05-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='room',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
