# Generated by Django 3.2.13 on 2022-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_auto_20220510_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_rent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=255, verbose_name='House Type'),
        ),
    ]
