# Generated by Django 3.2.13 on 2022-05-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0003_auto_20220510_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
