# Generated by Django 3.2.13 on 2022-05-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0004_alter_house_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='house_image',
        ),
        migrations.AddField(
            model_name='house',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='House/images/', verbose_name='House Image'),
        ),
    ]
