# Generated by Django 3.2.6 on 2022-05-12 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Agent', '0005_auto_20220511_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='avatar',
        ),
        migrations.CreateModel(
            name='House_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='House/images/', verbose_name='House Image')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='houseimage',
            field=models.ManyToManyField(to='Agent.House_Image'),
        ),
    ]
