# Generated by Django 3.2.6 on 2022-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0006_auto_20220512_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house_image',
            name='agent',
        ),
        migrations.AddField(
            model_name='house_image',
            name='house_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
