# Generated by Django 3.2.6 on 2022-05-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0007_auto_20220512_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_details',
            field=models.TextField(null=True),
        ),
    ]
