# Generated by Django 3.2.6 on 2022-05-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
        ('Agent', '0010_alter_house_user_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='user_message',
            field=models.ManyToManyField(blank=True, related_name='user_message', to='Chat.Message'),
        ),
    ]
