# Generated by Django 3.2.13 on 2022-05-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0011_alter_house_user_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_paid'],
            },
        ),
    ]
