# Generated by Django 3.2.13 on 2022-05-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0012_housepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housepayment',
            old_name='amout',
            new_name='amount',
        ),
    ]
